### ISSUE TITLE
Establish project management process

### ISSUE THREAD

**Issue by cbeams** [bisq-network/projects#1]
Board: https://github.com/orgs/bisq-network/projects/8

## Description

This project defines a project management process for the Bisq DAO.

## Rationale

_See also: https://bisq.wiki/Project_management#Purpose and https://bisq.wiki/Project_management#Philosophy_

Many if not most of the things we set out to accomplish under the Bisq DAO are best thought of and managed as _projects._ There are exceptions, such as simple bug fixes or carrying out the regular duties of a given role, but most efforts we undertake require multiple tasks and multiple contributors across multiple teams in order to be properly _delivered._ Modeling what we do as projects captures this reality and allows us to better manage it.

Projects provide a suitable unit of abstraction for budget allocation. As we have rolled out budgeting over the last weeks (#2), it has become clear that it is difficult to effectively allocate budget on a task-by-task basis. A better approach is to define a project up front and to estimate a budget for that project that includes all known tasks and teams that will be involved.

Projects allow us to scale out and deliver on more efforts in parallel. The project management process is designed such that any contributor can own a project from proposal to implementation to completion. Such a _project owner_ is responsible for every aspect of their project, including getting it approved, ensuring it stays on track and on-budget and reporting on it in a bi-weekly review. This of course does not mean that a project owner is responsible for _doing_ all the work necessary to deliver the project, but rather that the owner is responsible for ensuring the work _does get done._ In this way, we avoid the pitfall of centralizing all management to team leads, and instead build a culture of effective self-management with appropriate checks and balances.

Projects allow us to course correct on and/or disengage from efforts that are under-performing. If a project is blowing its budget, is suffering from scope creep, or has an owner that has gone awol, a project may be re-scoped or dropped entirely, allocating its budget elsewhere. Such decisions are made as part of the bi-weekly review process.

## Relationship to goals, proposals and processes

Projects are related to, but distinct from Goals. _Goals_ define high-level strategic outcomes for Bisq and the Bisq DAO as a whole (see the [Bisq Q1 2020 Update](https://github.com/bisq-network/admin/issues/5) for our current goals). _Projects_ are the tactical means by which we achieve those goals.

Projects are related to, but distinct from Proposals. _Proposals_ have become overused and in many cases, even when approved formally or informally, are effectively unimplementable or otherwise unmanageable because they do not define work and outcomes in enough detail. Going forward, proposals will continue to serve their function as a decision making mechanism within the DAO, but _projects_ will be the favored approach to managing efforts that require tasks, resources and time to accomplish.

Projects have an important relationship to Processes. _Processes_ such as proposals, compensation request reviews, DAO voting, role reporting, code reviews, and many others are activities that do not have a beginning and an end, but go on indefinitely and ultimately constitute _the way things work_ in the Bisq DAO. In some cases, the outcome of a project will be to establish a new process. The project you are reading about right now is one such example.

## Resources

See https://bisq.wiki/Project_management#Resources

## Roles and teams

See https://bisq.wiki/Project_management#Roles_and_teams

## Process

See https://bisq.wiki/Project_management#Process

## Criteria for delivery

- [x] The project management process proposed here has been proposed and approved (bisq-network/proposals#182)
- [x] The project management process is documented on the wiki at https://bisq.wiki/Project_management
- [x] An issue template is in place in the projects repository that captures the outline of a well-formed project definition (https://github.com/bisq-network/admin/issues/43)
- [ ] The bi-weekly project review meeting is scheduled and announced
  - UPDATE 2020.06.12: currently considering merging this review meeting with the new dev calls proposed at bisq-network/proposals#231
- [x] Existing projects are represented on the master projects board according to the documented process, i.e. with regard to columns and labels
- ~~Project owners of existing projects have agreed to attend the bi-weekly review meeting, and understand how to do a written report if they cannot make the call~~
- [x] Links exist that make the new process documentation easily discoverable
  - UPDATE 2020.06.12: Links exist in a number of places, but should double check that dev onboarding docs, contributing.md, etc have them as well.
- ~~Two full cycles have elapsed with the new process in place and all work that qualifies as a project is actually captured and being managed as a project. Team leads are directing contributors to propose projects where appropriate and are not allocating budget to multi-task efforts if they have not been proposed and approved as a project.~~
- ~~Learnings from the two full cycles have been incorporated into process and captured in the wiki documentation.~~

## Tasks

See the project board at https://github.com/orgs/bisq-network/projects/8.

## Estimates

This project is purely administrative, and administrative activities are not subject for compensation at the current time, so there is no cost estimate. It does consume the time and effort of the project owner (~~@cbeams~~ TBD), and of all those that help review and otherwise engage with the process proposed here, but these costs are considered to be integral to working within the dao, i.e. a cost of doing business.

**Comment by cbeams** [comment]
With regard to documenting this process, see https://github.com/bisq-network/projects/issues/7#issuecomment-587050443, where I explained to @m52go how things are designed to work in a nutshell.

**Comment by cbeams** [comment]
@bisq-network/team-leads, I've just fleshed out the description of this issue into a complete project proposal. It's rather meta, as this (first) project is about establishing a project management process, but you'll get the idea. The next step is to discuss this with the larger `@bisq-network/dao` team, so I'd appreciate your feedback on this as quickly as possible here as comments or in teamleads chat. At this point I'm just looking for any strong objections. If none, we can broaden the communication asap. Thanks.

**Comment by cbeams** [comment]
With bisq-network/admin#41, I've fleshed out the remaining tasks for this project and represented them on the dedicated project board at https://github.com/orgs/bisq-network/projects/8. I've removed all the checkboxes from the `Tasks` section of the description above and simply linked to the project board.

As a general note on the emerging process here, I have a feeling this (dedicated boards per project) is going to be my preferred approach as opposed to maintaining long lists of task checkboxes and bidirectional issue references in each project issue's description. Depends on how complex the project is, but in my experience, most have merited a board by the time the project is really in full swing.

**Comment by cbeams** [comment]
As per bisq-network/admin#48, I've just significantly revised the description of this project, simplifying it, removing unnecessary aspects, and referring to relevant sections of the newly-published https://bisq.wiki/Project_management article where appropriate.

**Comment by cbeams** [comment]
I've just updated the description to reflect current project status; bisq-network/proposals#182 has just been accepted, meaning that this process is "officially" adopted now. The dev calls proposed at bisq-network/proposals#231 can be used to implement the (bi-)weekly project reviews and really drive the project management process.

**Comment by cbeams** [comment]
Closing as delivered, with a couple caveats:

- The project review process is not yet locked in. As mentioned above, we're planning to use the new dev calls to implement this, but discussions are still underway as to exactly how this will go
- I've ~~crossed out~~ a couple tasks regarding folding in feedback to the process after two cycles of having it in the wild. This is because we've already had the process out there for more than two cycles, and it's clear that feedback and refinements will be an ongoing process.

In any case, all tasks on the associated project board are now complete. The infrastructure and process is out there, folks know about it, links exist in places that new contributors can easily discover the process, and now it's about making good use of it and refining it over time.

Also note that it is not yet clear who will "own" the process going forward. Discussions are underway now to eliminate the project management committee (@bisq-network/pmc) and replace it with a simple 'maintainer' role, but this has not yet been done.
