### ISSUE TITLE
Evaluate and improve account signing propagation

### ISSUE THREAD

**Issue by cbeams** [bisq-network/projects#10]
## Description
We have reason to believe that account signing protections rolled out in 2019 have not reached a critical mass of propagation in certain markets and may be impeding liquidity growth. This project exists to assess the actual state of propagation and take actions to improve it where necessary.

## Rationale
As it is critical to prevent scam attempts in markets with high liquidity with payment methods with a relatively high charge back risk we need to get the newly introduced account signing into a state where we reach and exceed past trading volumes again.

## Criteria
Based on the [account signing evaluation](https://github.com/bisq-network/admin/issues/10#issuecomment-588171825) I see this project delivered when we reach following goals in our major markets (EUR, USD) within the next three months:
- [ ] 75% of offers in offer book are made with signed accounts
  - [x] USD (Zelle)
  - [ ] EUR (SEPA, SEPA Instant)
- [ ] 50+% of trades are above 0.01 BTC
  - [ ] USD (Zelle)
  - [ ] EUR (SEPA, SEPA Instant)

## Tasks
- [x] @ripcurlx to evaluate current state of account signing propagation (bisq-network/admin#10)
- [x] @ripcurlx to evaluate current account signing process to find UX issues 
- [x] @ripcurlx to write up plan / tasks necessary to improve account signing propagation where necessary (UI/UX)
- [ ] @ripcurlx to write up plan / tasks necessary to improve account signing propagation where necessary (Signing process)

## Estimates
Will be posted as soon as required tasks are clear to make this project a success.

**Comment by ripcurlx** [comment]
@cbeams Could you give @bisq-network/team-leads the option to edit issues as well. In that case I want to adapt it to our desired project structure.

**Comment by cbeams** [comment]
Done. I thought Triage was going to be enough after all, but it's not. Team leads now have Write access now to this (projects) repository.

**Comment by mpolavieja** [comment]
@ripcurlx , @cbeams could you please consider to include this feature to improve the signing process?  Thanks.

https://github.com/bisq-network/proposals/issues/133

**Comment by cbeams** [comment]
@ripcurlx, I've marked this as stalled and returned it to the backlog to reflect that no activity / progress has been reported here for quite a while. I know you mentioned you're working on this in your last compensation requests; could you give a general update here? Feel free to remove the stalled label and put it back in progress if appropriate.

**Comment by pazza83** [comment]
Closing as stale
