### ISSUE TITLE
March 2020 Growth Reset

### ISSUE THREAD

**Issue by cbeams** [bisq-network/projects#14]
_This project was initially titled 'Bitcoin 2020' but has been renamed since the Bitcoin 2020 conference has been unexpectedly postponed._

Board: https://grow.bisq.cc/b/jPBBopYuLdGYdDpvF/markets

## Description

Bisq growth efforts in recent past have been relatively muted. Aside from documentation, resources to make using Bisq _simple_ have been scarce.

This effort aims to encourage volume in USD, EUR, and XMR throughout the month of March, through a series of content to encourage beginners and lurkers/tire-kickers, bots to promote good offers, and new payment methods to make bigger trades more quickly and easily...~capped off with Bitcoin 2020 at the end of the month.~

In addition to more volume, the content created with this initiative should serve as a foundation for ongoing growth efforts after March 2020 (more on this below).

Metrics:
- number of offers that go live in 24-hour period (not to be confused with number of offers live at any given moment)
  - goal: 1100; currently 600-700 on average but tops out around 800-900 on good days
- number of trades in 1 day
  - goal: 200; current record is 223 but that was more of an outlier (would like to see 200 trades hit on a more regular basis)
- average number of daily trades for March (would like to see February's average of 100 beat by 15+ percent)
  - goal: 115; previous record 100

## Tasks

_Content/Communications_

- [x] Announce March campaign across Bisq community channels: "Make the Market March" where we encourage all users to make 1 offer on Bisq
  - Running a Bitcoin node validates blocks for the Bitcoin network, but running a Bisq node does no good for the Bisq network without posting an offer.
  - Hammer home idea that Bisq liquidity is built by users - each user is their own source of liquidity to the network! So posting an offer really should be mandatory for anyone running Bisq.
  - **Encourage all users to post at least 1 offer on every Thursday in March**, hoping to hit higher and higher outstanding offers each week
- [x] Create web page as 1-stop destination with summary of efforts and progress 
- [ ] Release data on most likely-to-succeed Bisq offers
- [ ] [Release new video/article/guide _every day_](https://github.com/bisq-network/growth/issues/185) covering some key aspect of Bisq onboarding questions, trading process, etc.
- [ ] Hold calls on Thursdays to cover lingering concerns, objections, and feedback from community as final push for hitting weekly offer goal (sourced from #pulse Keybase channel)
- [ ] Loop in key communities like /r/bisq, /r/Bitcoin, /r/Monero, /r/BitcoinBeginners, /r/xmrtrader, etc. in weeks 2-3 to push even harder for higher offer numbers
  - Get in touch with moderators ~2 weeks in advance of desired posting date

_Tools (experimental but relatively low-effort)_

- [ ] Deploy Twitter bot to show off attractive Bisq offers (on a new handle), occasionally retweeting them from the main Bisq account, with aim of reducing time it takes for offers to be taken and thus increasing momentum
- [ ] Deploy inline Telegram bot so users can showcase real-time Bisq offer book on-demand in groups

_Payment Methods_

- [ ] Introduce payment methods in v1.2.8 that enable higher trading limits from day 1 of downloading Bisq (higher limits with no signing), **multiplying fiat trade sizes** and offering a host of additional benefits

_Event_

Only the magazine is slated to continue as planned...all other event preparations are postponed.

- [ ] Design magazine back cover
- [x] Design banner ad designs
~- [ ] Design stickers for distribution at event~
~- [ ] Design t-shirts for sale and distribution at the event~
~- [ ] Establish details for ID selfie photo booth: what's happening, what do we need to bring, who's bringing, etc~
~- [ ] Figure out how we can use the TV at the booth~
~- [ ] Collect list of all known contributors and users who will attend~
~- [ ] Create plan/schedule for volunteering (key responsibilities) at the event~

**Comment by m52go** [comment]
March is long-gone now. This initiative had some success, it was a big learning event for me, and it certainly served as a spark for other ideas and initiatives. New projects and initiatives will be created to carry on any loose ends here. 

The most direct successor to this project is [here](https://github.com/bisq-network/growth/issues/196).

**Comment by pingiun** [comment]
> Deploy Twitter bot to show off attractive Bisq offers (on a new handle), occasionally retweeting them from the main Bisq account, with aim of reducing time it takes for offers to be taken and thus increasing momentum

I have done this! It's available at https:/t.me/bisqbot
