### ISSUE TITLE
Create more detailed offerbook metrics

### ISSUE THREAD

**Issue by freimair** [bisq-network/projects#22]
# Description

In order to make more informed decisions in the field of growth efforts, we have to better understand our markets. @m52go came up with the idea that we need to understand why a particularly good day (in terms of trading volume) happened, so that we may learn to tweak the environment to make such a "good day" more likely. Understanding a bygone offer book seems like a good place to start. However, memorizing the whole offer book is impractical and a potential privacy leak.

## Proposed solution

Thus, we agreed on 3 additional data histogram streams (for each market) to be included on https://monitor.bisq.network/ (based on [this](https://github.com/bisq-network/bisq/issues/3916#issuecomment-588294997)):
1. trader distribution by offers
This lets us make statements like
   - the top 20% of all traders produce 80% of all offers
   - 40% of traders only have 1 or 2 offers open
1. trader distribution by volume
    - the top 20% of all traders have 90% of volume on offer
    - 60% of traders have < 0.2 BTC on offer
1. volume per offer
    - 80% of offers cause only 10% of volume
    - there are no offers for volumes between 0.2 BTC and 1 BTC

These data also allows for statements like
- there are offers for every volume, small to big
- we have many traders with a good spread of volume per offer, if we loose a couple of these, the market is still healthy
- a very small number of traders create most of the volume, if we loose a couple of these, the market might die

## Implementation details

Note that these metrics are designed to give a quick idea on how the offer books looked like. The data is no simple statistical data stream providing averages, extrema or percentiles, instead, we use data binning. Here is an example graph showing "trader distribution by offers":

![Screenshot from 2020-02-25 16-03-10](https://user-images.githubusercontent.com/1070734/75259478-64990300-57e8-11ea-9337-9a85a380e8ea.png)

additionally, we know that the top trader has 12 offers.

| data series index | offers per trader | textual description |
| --- | ---:| --- |
| 0 | 1, 2 (0-2.4) | traders which have less than 20% offers active than the top trader has by count |
| 1 | 3, 4 (2.4-4.8) | traders which have between 20% and 40% offers active then the top trader has by count |
| 2 | 5, 6, 7 (4.8-7.2) | traders, 40-60% |
| 3 | 8, 9 (7.2-9.6) | traders, 60-80% |
| 4 | 10, 11, 12 (9.6-12) | top 20% of traders, by offer count |

The data of the 4 time stamps in the graph above are crafted for demonstration purposes:
- T=4: there are 13 traders, all of them have 10, 11, or 12 offers. There is no "casual" trader.
- T=3: there are 15 traders, one of them has 12 offers, all others have 1, 2 or 3 offers each.
- T=2: there are 15 traders, every kind of trader is present, the most casual trader up to and including the most involved trader.
- T=1: the actual measured BSQ buy market offer book of 2020-02-25 16:00 CET.

If these metrics turn out to be useful, we can think of creating the same set of data streams for trades.

# Criteria for Delivery

Make the data visible as graphs on https://monitor.bisq.network/.

# Tasks

- [x] design metrics
- [x] proof of concept implementation
- [x] update monitoring daemon
- [ ] deploy monitoring daemon
- [ ] configure https://monitor.bisq.network/

# Estimates

USD 750,00 as already [stated](https://github.com/bisq-network/bisq/issues/3916#issuecomment-588294997)

**Comment by chimp1984** [comment]
@ripcurlx @cbeams Can we close that project?
