### ISSUE TITLE
Migrate to Tor v3 onion service protocol

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/projects#24]
## Description
This project is about migrating from Tor Hidden Services version 2 to Tor onion services version 3 and the required steps to do so. 

### Why do we want to update?
- we expect significant improvements during startup? - yes
- improves security/privacy? - yes (better crypto, no longer sha1)
- solves our connection issue with seednodes,...? - unknown, maybe
- we expect a positive performance impact on the Bisq network? - ?
- we expect fewer timeouts? - ?
- we have to upgrade at some point - is that so? - no reason that we know of now
- fixes issue: https://github.com/bisq-network/bisq/issues/3987? - ?

## Criteria for delivery

 - [ ] All new Bisq clients are v3 by default
 - [ ] 

## Milestones

# Proof of concept
  - upgrade v2 to v3 in a branch, deploy a test network and test all platforms, mix of v2 clients and v3
  - measure performance improvements, if any
  - decide whether to move forward
# Ship it
  - all new clients use v3 hostnames
  - all existing seednodes use v2
  - one new seednode use v3 hostname
  - wait and see how it goes over time
  - look to support team to report potential issues
  - checkpoint - do we go on with milestone 3? at what scope?
# Allow old clients to upgrade
  - support renewal feature
  - reputation migration?

## Tasks
- [x] add support for Tor onion services v3 in our legacy clients
- [ ] evaluate performance improvements -> what would be a success for this upgrade?
- [ ] update tor binary and use v3 onion services by default for new clients
- [ ] enable users to renew onion addresses, warning them that reputation is not transfered
- [ ] transfer reputation when migrating from Tor Hidden Services version 2 to Tor onion services version 3

**Comment by ripcurlx** [comment]
Superseded by https://github.com/bisq-network/projects/issues/23

**Comment by cbeams** [comment]
Thanks, @ripcurlx. Note that I've just added the `was:superseded` label. It's important from the Master Projects Board perspective to see a `was:*` label on each closed project, so it's easy to distinguish which were delivered / dropped / superseded, etc.
