### ISSUE TITLE
Integrate advice throughout software to improve UX

### ISSUE THREAD

**Issue by m52go** [bisq-network/projects#38]
> _This is a Bisq Network project. Please familiarize yourself with the [project management process](https://bisq.wiki/Project_management)._

## Description

In the absence of a [truly-improved onboarding wizard](https://twitter.com/bisq_network/status/1230958568943292417), we can improve and add text throughout the software to make Bisq easier to use.

I think this initiative is different from #12 because it has more to do with in-the-moment usage of the software, which is distinct from onboarding (thoughts welcome if I'm wrong about this).

## Rationale

There is lots of documentation and videos now on the wiki and YouTube, but most users don't ever read or watch it. This leads to rough onboarding, confusion, more support questions, and in extreme cases—abandonment.

## Criteria for delivery

A list of improvements will be suggested, and this project can be considered delivered when those improvements are implemented in the software.

## Measures of success

We should see reduced support queries for simple common items like how to back up data directories, etc. Otherwise I'm not sure which metrics to track to measure success...we could do a sample set of user-testing before and after, but I'm not sure it's worth the time.

I seek to address issues and pain points that we see repeatedly throughout social and support channels, so the problems are worth solving by definition.

## Risks

No risks. This effort requires mostly string changes.

## Tasks

- [ ] determine pain points in current software from common questions on Keybase, forum, GitHub, etc. as well as support staff
- [ ] devise solution for pain point (improved string, improved modal, etc)
- [ ] implement solution in software

## Estimates

100 USD for surveying and determining pain points
300 USD maximum for string changes (displayStrings.properties file)
Budget for software changes is for developers to decide, but should not be significant

## Notes

None.

**Comment by m52go** [comment]
In surveying the software for this project, I found it useful to update strings. Many strings have awkward wording that can result in confusion, while others are simply out-of-date, so a thorough update seems worthwhile.

https://github.com/m52go/bisq/tree/refresh-strings-1
https://github.com/m52go/bisq/tree/refresh-strings-2

**Comment by Bayernatoor** [comment]
I agree with this. I did make changes to strings a few months back since some of the wording was confusing/grammatically incorrect. But I never did make a PR  for those changes. 

Anyway correcting the text on the application could help improve user experience and make the platform more "professional" since typos, grammatical errors etc can be a turn off for users.

@m52go Did you want help on this or are you handling it?

**Comment by m52go** [comment]
Yes I started this and made a couple of PRs ready that I never submitted and then got diverted by other work. I would like to at least have strings improved and submit a preliminary list of suggested additions to developers in this cycle.

I could probably use help, yes, and your support insight might be especially helpful. Might be easier to coordinate this 1-1, maybe through chat or another call.

**Comment by MwithM** [comment]
I wasn't thinking on this project when I submitted this issue, but reacting to a user error. https://github.com/bisq-network/bisq/pull/4379
Anyway, I think it's worth to bring it here. Thanks to devs for addressing it so quickly.

I would also like to point this issue about security deposit display. I'm not sure what change should be performed, but something needs to be done since I don't know how to know what's the recommended security deposit.
https://github.com/bisq-network/bisq/issues/4426

I'll take a look at other possible changes from last Keybase and reddit requests.

**Comment by pazza83** [comment]
Closing as not completed / stale
