### ISSUE TITLE
Reduce or eliminate arbitration cases

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/projects#39]
> _This is a Bisq Network project. Please familiarize yourself with the [project management process](https://bisq.wiki/Project_management)._

## Description
Reduce or in best case eliminate arbitrator cases (refund agent cases). 

## Rationale
The v2 of the Bisq trade protocol was designed to handle a handful of arbitrator cases each month. Right now it is more like 1+ cases per day which is not sustainable and creates an unnecessary load on arbitrators.

This resulted in multiple proposals:
- [Concerning the refund agent system](https://github.com/bisq-network/proposals/issues/236)
- [Allow seller to be offline and still get the payout tx signed for altcoins](https://github.com/bisq-network/proposals/issues/241)
- [Action Protocol for Mediators](https://github.com/bisq-network/proposals/issues/237)
- [Allow trader negotiation of disputed BTC payout](https://github.com/bisq-network/proposals/issues/234)
- [Proposal to increase trade deposit to 30%](https://github.com/bisq-network/proposals/issues/233)
- [Trading protocol change: release of funds in 2of2 multisig to be signed by seller in first place](https://github.com/bisq-network/proposals/issues/224)

PRs:
- [Deposit improvements](https://github.com/bisq-network/bisq/pull/4347)

It is required that we solve this problem one way or the other to reduce total trade time in case of arbitration and not to loose the arbitrator before an acceptable alternative is available.

## Criteria for delivery / Measures of success
- [ ] 3 arbitration cases/cycle if we have 3000 trades/cycle
- [ ] refunds without arbitrator (mediator & DAO)

## Tasks
- [ ] Communicate penalty of trade protocol violation within trade process
- [ ] Improve badge notification system to show indicator only if there is an open task to fulfill
- [ ] Add desktop notifications
- [ ] Enable mobile notifications for trading peer if available

## Estimates

This project has no estimates as it is more an [epic story](https://www.agilealliance.org/glossary/epic/#q=~(infinite~false~filters~(postType~(~'page~'post~'aa_book~'aa_event_session~'aa_experience_report~'aa_glossary~'aa_research_paper~'aa_video)~tags~(~'epic))~searchTerm~'~sort~false~sortDirection~'asc~page~1)). The tasks or proposals that we agree on working will have estimates instead.

**Comment by ripcurlx** [comment]
We shipped a deposit percentage suggestion based on volatility in v1.3.7. It seems to be helping, but it didn't reduce the refund agent cases to an acceptable level. So we need to continue with the improvements mentioned above and to find out the root cause of unresponsive sellers in the Monero market.

**Comment by pazza83** [comment]
Closing as superseded
