### ISSUE TITLE
Update to LTS Java version

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/projects#44]
> _This is a Bisq Network project. Please familiarize yourself with the [project management process](https://bisq.wiki/Project_management)._

## Description
We need to update our Java and JavaFX version to be able to fix critical memory and UX issues with the current Java(10)/JavaFX(11) version we are using. Also we need to move to a LTS java version to receive ongoing security updates.

## Rationale
After Oracle ripped out the javapackager (required to create binaries for macOS, Windows and Linux OSes), we got stuck with the last Java version still including the javapackager - Java 10. The support for Java 10 ended already in March 2018 which means we didn't receive security updates since that point of time. Issues regarding the situation we are in are stacking more and more up and we need to have a path to update to a LTS java version sooner than later. This was blocked for a long time by the lack of a javapackager replacement. It seems to be that the [Packaging Tool](https://openjdk.java.net/jeps/343) is ready (resolved 2020-02-05) so it make sense to start the upgrade work now.

### Issues related / likely related to this project
- [Bisq requesting permissions for keystrokes on all apps [osx catalina]](https://github.com/bisq-network/bisq/issues/3373)
- [System tray not visible on some Linux distributions
](https://github.com/bisq-network/bisq/issues/350)
- [Improve spinner performance](https://github.com/bisq-network/bisq/issues/2135)
- [Application freezes on take offer screen](https://github.com/bisq-network/bisq/issues/2509)
- [Memory Leak - Ubuntu 18.04 LTS](https://github.com/bisq-network/bisq/issues/3128)
- [Bisq using way too much RAM on windows](https://github.com/bisq-network/bisq/issues/3307)
- [Bisq UI very laggy/slow on Windows 8](https://github.com/bisq-network/bisq/issues/3308)
- [Java Heap Space - Qubes](https://github.com/bisq-network/bisq/issues/3343)
- [Bisq taking more than 2GB of memory during startup](https://github.com/bisq-network/bisq/issues/3430)
- [Hangs the whole OS on startup. Ubuntu 19.10](https://github.com/bisq-network/bisq/issues/3657)
- [Investigate if -BjvmOptions for linux build is still needed](https://github.com/bisq-network/bisq/issues/3677)
- [High resource usage and responsiveness problemsHigh resource usage and responsiveness problems](https://github.com/bisq-network/bisq/issues/3683)
- [Does not start in VirtualBox Debian (latest) guest](https://github.com/bisq-network/bisq/issues/3686)
- [Java heap space error MacOS Bisq](https://github.com/bisq-network/bisq/issues/3786)
- [Java Heap Space Windows 10, low resource VM](https://github.com/bisq-network/bisq/issues/3787)
- [Java Heap crash on ubuntu 19.10, bisq 1.2.5](https://github.com/bisq-network/bisq/issues/3892)
- [bisq freezes entire pc on arch linux](https://github.com/bisq-network/bisq/issues/3917)
- [Bisq using up too much memory on Linux even after closing](https://github.com/bisq-network/bisq/issues/3918)
- [Java Heap Space](https://github.com/bisq-network/bisq/issues/3936)

## Criteria for delivery / Measures of success

This project is delivered if Bisq can be built with a LTS Java version and the latest JavaFX version and it still is possible to build binaries for Linux (deb, rpm), Windows (exe) and macOS (dmg).

## Risks

The efforts could increase exponentially, because of unknown obstacles (we did have this issues in the past already). This could slows down all other development if severe changes to the build pipeline are necessary. To mitigate this risks we should focus on the absolute minimum requirement for each milestone to find out about critical issues as early as possible.

## Tasks/Milestones

- [ ] Use jpackage from JavaFX 15 and build binaries for Linux (deb, rpm), Windows (exe) and macOS (dmg) using Java 11 JDK (closest LTS)
- [ ] Update JavaFX from 11 to 15
- [ ] Add Rasperry Pi zip
- [ ] Optional: Use jlink to build a custom made JRE to reduce size of installer (maybe also improves required memory footprint)
- [ ] Optional: Extend build pipeline to include notarization step for macOS as well (https://github.com/bisq-network/bisq/issues/3402). See answers for 
- [ ] Optional: Create a deterministic build

## Estimates

It is hard to estimate as it is lots of investigation and try and error involved. But @cd2357 seems to be quite far already (see https://github.com/bisq-network/bisq/pull/4242)

**Comment by cd2357** [comment]
@ripcurlx can this be considered done? If yes, I can close it.
