### ISSUE TITLE
Improve support and mediation

### ISSUE THREAD

**Issue by huey735** [bisq-network/projects#48]
> _This is a Bisq Network project. Please familiarize yourself with the [project management process](https://bisq.wiki/Project_management)._

## Description

The support and mediation provided by the Bisq contributors has a lot of room to improve. The goal of this project is to come up with ways to create standards and resources that the contributors and traders can refer to and use for better experience.

## Rationale

It's important we have an agreed upon set of solutions, standards and responses that all support agents and mediators can refer to so that suggestions don't change drastically from person to person and from case to case.

## Criteria for delivery

- code of conduct document for mediation
- list of most common bugs and their known fixes
- script to make mediation uniform
- table of penalties, case by case

## Risks

None

## Tasks

- [ ] Update [library of known bugs](https://bisq.wiki/Support_Agent#Knowledge_base_for_support) and their fixes
- [ ] Create a code of conduct for mediation on the wiki
- [ ] Create a script for support and mediation on the bisq-network/support repository
- [ ] Create table of penalties

## Estimates

Not defined.

**Comment by huey735** [comment]
@bisq-network/support

**Comment by pazza83** [comment]
Hi @huey735 is any one putting together a 'code of conduct document'?

I would be happy to produce one for discussion / feedback if one has yet to be created.

**Comment by pazza83** [comment]
Here are my suggestions for the code of conduct:

## Bisq Mediation - Codes of conduct

For traders entering mediation in Bisq this is what they can expect from mediators:

- Mediators will adopt a neutral stance
- Mediators will reveal any potential conflicts of interest
- Mediators will maintain the confidentiality of all traders
- Mediators will direct traders to appropriate resources
- Mediators will possess the necessary competence and knowledge about to deal with the dispute
- Mediators will act fairly, independently and impartially
- Mediators will record their decision in writing at the end of the meditation process and make this available to all traders and arbitrators
- Mediators will respond to messages within 24 hours

For traders entering mediation on Bisq this is what mediators expect from all parties:

- Traders will keep conversation friendly and respectful
- Traders will make themselves aware of Bisq's trading protocol
- Traders will make themselves aware of Bisq's dispute resolution process
- Traders will provide mediators with the necessary information when opening a dispute
- Traders will respond to messages within 48 hours

**Comment by leo816** [comment]
> Mediators will respond to messages within 48 hours
* Mediators will respond to messages within 24hrs.

Will add this to the wiki. Thank you @pazza83

**Comment by pazza83** [comment]
Thanks, included your update

**Comment by pazza83** [comment]
The trade penalties aspect of this is now complete. I have just closed the issue: [Display link to the dispute resolution process including table of trade penalties at relevant points in trade process](https://github.com/bisq-network/bisq/issues/5456)

The penalty info is now linked from both the wiki and the Bisq client.

I will keep the table updated with any new scenarios that occur.

**Comment by pazza83** [comment]
Closing as completed
