### ISSUE TITLE
Integrate wallet and blockchain data modules in Misq

### ISSUE THREAD

**Issue by ghost** [bisq-network/projects#58]
## Description

Further to #52, this project is to integrate Bitcoind and Electrum wallets functionally within the Misq project.  This will permit Misq trading and funds transfer to be performed using either of these two different wallets.

## Rationale

A large part of Misq goal is to have the ability to choose between different third party wallet implementations.  Without it we would be joined at the hip to BitcoinJ as is the case with Bisq.

## Criteria for delivery

The project will be complete when you can make trades in Misq using either Bitcoind or Electrum wallets.

## Measures of success

Misq trading can be performed.  It will be worthwhile for people to onboard to Misq due to the flexibility and reliability improvements that having different wallet options affords.

## Risks

Diverts developer energy to the Misq project, away from Bisq.

## Tasks

- [ ] Migrate from Proof of Concept wallet API (#52) to production ready wallets API.  This will evolve as other areas of Misq are fleshed-out.
- [ ] Integrate with the results of #53 so that wallet modules may be loaded dynamically into Misq.
- [ ] Integrate with the results of #54 so that wallet modules may be used for trading.
- [ ] Integrate the wallet API with the Misq codebase, specifically for Trading and Funds transfer.  This will require collaboration with other Misq developers.
- [ ] Implement a setup, connection & status UI for the chosen wallets (i.e. connect to MyNode).
- [ ] Packaging, download & run of Electrum daemon within Misq client.

## Estimates

$15K USD when the Misq project is able to do live trades.
Current estimate is that it would take 6 months to bring Misq to that state; that is the duration of this sub-project.

**Comment by ghost** [comment]
Closing this as I'm not satisfied with the incentive structure of having only a single deliverable at the end of the project.  I'm guessing a better project proposal would have more steps that can be achieved in smaller timeframes.
