### ISSUE TITLE
Integrate Bitcoind as a wallet backend into Misq

### ISSUE THREAD

**Issue by alvasw** [bisq-network/projects#62]
> _This is a Bisq Network project. Please familiarize yourself with the [project management process](https://bisq.wiki/Project_management)._

## Description

This project integrates Bitcoind as a wallet backend into the Misq project. In Misq, we allow users to select between multiple wallets (see #52).

## Rationale

In Misq, we want to break away from developing our own wallet. There are a lot of excellent wallets with which we can communicate using RPC calls.

## Criteria for delivery

This project is complete when the needed RPC calls to Bitcoind are implemented and merged into the Misq project (including integration tests).

## Measures of success

We have our first full node wallet backend in Misq.

## Risks

None for the DAO. The only thing that can happen is that I fail to deliver.

## Tasks

- [x] Bitcoind Process Manager (startup & shutdown)
- [x] RPC Connection to Bitcoind
- [x] RPC calls:
    - [x] `addmultisigaddress`
    - [x] `createwallet`
    - [x] `finalizepsbt`
    - [x] `generatetoaddress`
    - [x] `getaddressinfo`
    - [x] `getbalance`
    - [x] `getnewaddress`
    - [x] `importaddress`
    - [x] `listtransactions`
    - [x] `listunspent`
    - [x] `loadwallet`
    - [x] `sendrawtransaction`
    - [x] `sendtoaddress`
    - [x] `signmessage`
    - [x] `stop`
    - [x] `unloadwallet`
    - [x] `verifymessage`
    - [x] `walletcreatefundedpsbt`
    - [x] `walletpassphrase`
    - [x] `walletprocesspsbt`
- [x] Integration test for all RPC calls

## Estimates

USD 600
