### ISSUE TITLE
Bisq2: Create Wallet Prototype UI To Test Wallet Functionalities

### ISSUE THREAD

**Issue by alvasw** [bisq-network/projects#63]
> _This is a Bisq Network project. Please familiarize yourself with the [project management process](https://bisq.wiki/Project_management)._

## Description

In bisq-network/projects#62 I implemented Bitcoin Core as a wallet backend. The pull request bisq-network/bisq2#16 was merged two weeks ago. @chimp1984 suggested creating a UI prototype for the wallet before implementing the Electrum RPC. Bisq2 does not have a UI yet, so this would help us test the wallet functionalities (send, receive, ...) more smoothly and find bugs early. I'll write the UI against a wallet interface to be able to test the other wallet implementations with the same UI.

## Rationale

Bisq2 supports Bitcoin Core as a wallet backend (bisq-network/projects#62). A UI would help us test the wallet functionalities (send, receive, ...) more smoothly and find bugs early.

## Criteria for delivery

- [x] Ability to open multiple of wallets (Alice, Bob, Charlie) and play with them.
- [x] Display Balance
- [x] List Transactions (TxId, Address, Amount, Confirmations)
- [x] Send BTC
- [x] Generate new addresss (receive)
- [x] List UTXOs (TxId, Address, Amount, Confirmations, Reused)

Anything missing or you like to add? @chimp1984

## Measures of success

We should be able to test the wallet functionalities (send, receive, ...) more smoothly and find bugs early.

## Risks

None.

## Tasks

- [X] Build UI
  - [X] Display Wallet Name
  - [X] Display Balance
  - [X] List Transactions (TxId, Address, Amount, Confirmations)
  - [X] Send BTC
  - [X] Generate new addresss (receive)
  - [X] List UTXOs (TxId, Address, Amount, Confirmations, Reused)
- [x] Create Interface to
  - [x] Get Balance
  - [x] List Transactions (TxId, Address, Amount, Confirmations)
  - [x] Send BTC
  - [x] Generate new addresss (receive)
  - [x] List UTXOs (TxId, Address, Amount, Confirmations, Reused)
- [x] Connect UI to WalletService

**Comment by alvasw** [comment]
My progress so far.

|    |   |
| ------------- | ------------- |
| ![bisqd_1_txs](https://user-images.githubusercontent.com/95712046/148646706-da97a506-986b-427a-bccb-b9a4ef77eff4.png)  | ![bisqd_2_send](https://user-images.githubusercontent.com/95712046/148646712-d675d1d6-535b-4ba9-ace8-a436f74641e2.png)  |
| ![bisqd_3_recv](https://user-images.githubusercontent.com/95712046/148646719-d59d633d-01d2-424d-b1ce-fcf8fa2f4f79.png)  | ![bisqd_4_utxos](https://user-images.githubusercontent.com/95712046/148646722-891efe4a-d792-41c6-afc8-43a0889e8b6a.png)  |

**Comment by chimp1984** [comment]
> Ability to open multiple wallets (Alice, Bob, Charlie) and play with them.

Does that mean multiple wallets in the same app or just starting different apps with different wallets?
I think the latter is enough.

**Comment by alvasw** [comment]
When I started this task, I wasn't sure about the details. I took your network monitor UI as inspiration.

**Comment by alvasw** [comment]
The final result:
|    |   |
| ------------- | ------------- |
| ![bisq2_wallet_1](https://user-images.githubusercontent.com/95712046/153057128-a3bce677-0c55-45d0-89a8-ea636fc649a4.png) | ![bisq2_wallet_2](https://user-images.githubusercontent.com/95712046/153057138-5251df32-8486-4eef-8f02-8043df425d88.png) |
| ![bisq2_wallet_3](https://user-images.githubusercontent.com/95712046/153057148-7102998e-232e-44db-9a1b-1705d9c4c1e1.png) | ![bisq2_wallet_4](https://user-images.githubusercontent.com/95712046/153057156-e23e049f-ad54-4dfb-8a7f-1a8a1dc25845.png) |

**Comment by alvasw** [comment]
This project is completed.

- bisq-network/bisq2#51
- bisq-network/bisq2#73
- bisq-network/bisq2#74
- bisq-network/bisq2#81
- bisq-network/bisq2#82
