### ISSUE TITLE
Bisq2: Liquid Wallet Integration (Elements)

### ISSUE THREAD

**Issue by alvasw** [bisq-network/projects#64]
> _This is a Bisq Network project. Please familiarize yourself with the [project management process](https://bisq.wiki/Project_management)._

## Description

We want to implement atomic swaps between Bitcoin and L-BTC/Liquid Assets in Bisq 2. To do that, we need to implement a Liquid Wallet backend first. In this project, I'll implement the backend for the Elements Wallet (https://blockstream.com/elements/).

## Rationale

This is needed to implement atomic swaps between Bitcoin and L-BTC/Liquid Assets.

## Criteria for delivery

This project is complete when the needed RPC calls to Elements are implemented and merged into Bisq 2 (including integration tests).

## Measures of success

We have a liquid wallet in Bisq 2.

## Risks

None.

## Tasks

- [x] Setup Elements Wallet with Bitcoin Core Regtest Instance
  - [x]  Create Elements Process Manager (startup & shutdown)
- [x] Bitcoin RPC calls:
  - [x] getrawtransaction
  - [x] gettxoutproof
- [x] Elements RPC calls:
  - [x] claimpegin
  - [x] createwallet
  - [x] finalizepsbt
  - [x] generatetoaddress
  - [x] getbalance
    - [x] L-BTC
    - [x] Liquid Assets
  - [x] getnewaddress
  - [x] getpeginaddress
  - [x] getrawtransaction
  - [x] gettxoutproof
  - [x] issueasset
  - [x] listtransactions
  - [x] listunspent
  - [x] listwallets
  - [x] loadwallet
  - [x] sendrawtransaction
  - [x] sendtoaddress
    - [x] L-BTC
    - [x] Liquid Assets
  - [x] signmessage
  - [x] stop
  - [x] unloadwallet
  - [x] verifymessage
  - [x] walletpassphrase
- [x] Integration test for all RPC calls

**Comment by alvasw** [comment]
Delivered in https://github.com/bisq-network/bisq2/pull/111.
