### ISSUE TITLE
Lightning node implementation for LN trades

### ISSUE THREAD

**Issue by salokiam** [bisq-network/projects#66]
## Description
This proposal is the first step towards trades through lightning. By starting this I hope to better attract other developers to join the effort, because they see there is some activity in regard to the lightning protocol. The project will be one of the basic steps we anyway need for going the lightning route. It installs a customizable lightning node which is able to process a payment.       
We need a Lightning node functionality in Bisq2, see [Proposal 373](https://github.com/bisq-network/proposals/issues/373). This project will incorporate LDK ([Lightning Development Kit](https://lightningdevkit.org/)) as node implementation into Bisq2.

## Rationale

This is a necessary building block for the lightning trade protocol. Many more steps need to be made to have the full functional lightning trade protocol. However, this is a fist step towards the (long-term) goal.
## Criteria for delivery

This project will be completed, when the LDK is added to bisq2 and an implementation on top of the LDK is capable of running a payment.The lightning node implementation will be installed with gradle task automatically.
## Measures of success

Bisq2 will have a working lightning node, which can handle payments on testnet.
## Risks

None.
## Tasks

This will integrate the LDK with Bisq2 as a first step. This is not a fully fledged Node implementation with all bells and whistles. It's just the first step in development process to get the hands around to build a LN node to run a minimal version.
- [ ] Include LDK in build system, access to bitcoin node needs to be configurable.
- [ ] Implement sample Lightning node using LDK
  - [ ] Create sample FeeEstimation
  - [ ] Integrate with our Logging System
  - [ ] Integrate our NetWork with the node's BroadcasterInterface
  - [ ] Provide a NetworkGraph implementation for routing Payments
  - [ ] Integrate the persistence with our PersistenceStore
  - [ ] Sample implementation of EventHandler 
  - [ ] Implement ChainMonitor to get Block-infos from BitcoinCore
  - [ ] Provide sample KeysManager 
  - [ ] Persist ChanelMonitors
  - [ ] Implement ChannelManager for managing the channels states.
  - [ ] Sync channel states with blockchain
- [ ] Test Lightning node making a payment. Since we don't integrate a lightning wallet at this time, this will remain a description of steps how to manually test the lightning node.

## Estimates
Project duration: until end Feb 2023

Costs: USD 4000
## Notes
note that Lightning nodes depend on a bitcoin node (or Electrum). This project will not implement a bitcoin node. It will depend on an existing bitcoin node to access.

**Comment by HenrikJannsen** [comment]
I think before investing in a LN integration we need to have more clearity about the LN trade protocol and roadmap how we can implement that. The [author](https://github.com/stejbac) of the the [proposal](https://github.com/bisq-network/proposals/issues/373) has not been active since May 2022 and I fear we cannot count on him that he will implement it and finalize the concept (I guess there have been a few uncertainties still). I hope very much that he will be able to implement it at some point but we cannot simply assume that we are able to implement that sophisticated protocol if he is not available. It contains some cutting edge cryptography (garbled circuits) and beside @alvasw we do not have a developer with extensive experience in cryptography and I doubt that @alvasw will be available for such a large and challenging project any time soon.

Beside that, it might be that the protocol has requirements on a LN implementation which might not be covered by the suggested one. This is a speculative point as I am not sufficiently familiar with the protocol and LN, I just wanted to mention it as a risk that we might integrate something which would need to be replaced then later when it turns out it cannot be used with the protocols requirements.

So I don't think we have the luxury that we can fund such a project without having a very clear and realistic path how we can utilize it.

**Comment by salokiam** [comment]
Thanks for the quick response. This was a long shot anyway. I understand that the chances of this project being actually beneficial might be too low.
