### ISSUE TITLE
Roll out the Bisq Wiki

### ISSUE THREAD

**Issue by cbeams** [bisq-network/projects#8]
Board: https://github.com/orgs/bisq-network/projects/14

## Description

Introduce a MediaWiki instance at https://bisq.wiki, initially for the purpose of a Bisq support knowledge base, but eventually to replace docs.bisq.network.

This project is Phase 1: standing up and effectively rolling out the wiki
Transcribing and potentially decommissioning docs.bisq.network is Phase 2 and will be managed as a separate, follow-on project.

## Rationale

Why a wiki: ease of use, quick access, no technical / process barriers. Review after-the-fact, not before. Our current docs infrastructure is great, but has a high barrier to participation. This wiki will be open to the public / community. Inspiration: the Bitcoin wiki at https://en.bitcoin.it.

Why Mediawiki: most capable, most widely known and used, open source, same as used by the Bitcoin wiki, so familiar for the community.

## Criteria for delivery

- [ ] `@bisq-network/support-agents` are referencing KB articles in support cases as appropriate, editing and writing new KB articles as appropriate. (How do we measure this?)
- [ ] Wiki has a Bisq branded look and feel
- [ ] Wiki has a useful main page that directs users to various kinds of content within
- [ ] One or more docs from docs.bisq.network have been migrated to wiki. docs.bisq.network does NOT have to be decommissioned completely for this project to be considered delivered.
- [ ] Placeholder docs exist on wiki for all docs.bisq.network pages that have not been moved consisting of just a link back to the docs site. This is in order to be able to quickly treat the wiki as a complete / canonical source of information.
- [ ] Many `@bisq-network/dao` contributors have created a login and made edits
- [ ] Multiple users (outside the Bisq DAO) have created logins and made edits, i.e. we have reason to believe that we have effectively gotten the word out.

## Tasks

Tasks are managed on the project board at https://github.com/orgs/bisq-network/projects/14.

**Comment by m52go** [comment]
@cbeams are we looking to make an "official" announcement to roll out the wiki? 

So far it seems we're adding articles and linking to them as it's expedient...would it be acceptable to do this more publicly right now (i.e., Twitter), or would it be better to wait until a certain time (e.g., when this project is marked delivered)?

Specific example: want to promote L-BTC trading on Bisq, make video, and tweet...can/should link to L-BTC wiki article be included for additional background?

**Comment by cbeams** [comment]
Please link to specific articles as necessary. We shouldn’t announce anything at least until we have a proper main page.

**Comment by cbeams** [comment]
Per https://github.com/orgs/bisq-network/teams/dao/discussions/13, I've just unassigned myself from owning this project, marked it as `is:stalled` and put it back into the `Backlog` column of the Master Projects Board.

Properly completing this project should probably be owned by the future Support Team Lead (bisq-network/roles#102)

**Comment by cbeams** [comment]
Per agreement on yesterday's team leads call (bisq-network/teamleads#2), @m52go will own this project going forward. Indeed, he has been effectively driving it anyway, and much progress has been made. I've removed the stalled labeled, and will let you, @m52go, do as you see fit with the remaining issues on the associated project board. Please just update / rework things as it makes sense to you to do / as reflects the reality of what you're doing.

**Comment by cbeams** [comment]
Note we can also mention the rollout on the Q2 Update call (bisq-network/admin#81).

**Comment by m52go** [comment]
Just updated the front page, and most pages are edited. 

All pages linked on the new getting-started page are edited. A small handful of others remain, but they're not critical for rolling out the wiki (in my opinion)...and of course it's a wiki, so it will never be 100% perfect. 

I'd say it's ready to go. Requesting feedback on Keybase now.

**Comment by m52go** [comment]
Announced on the [Q2 2020 call](https://www.youtube.com/watch?v=k_QjrhU3hrc), and linked on the [new getting-started page](https://bisq.network/getting-started/).

Closing as complete.
