### ISSUE TITLE
Clean up roles and bonding

### ISSUE THREAD

**Issue by cbeams** [bisq-network/projects#9]
Project board: https://github.com/orgs/bisq-network/projects/10

 - [ ] Decide on and communicate how we will handle bond interest (bisq-network/admin#30)
 - [ ] Assess the state of all roles and bonds (bisq-network/admin#4)
 - [ ] Follow up with owners to close any gaps
 - [ ] Transcribe http://docs.bisq.network/roles.html documentation to wiki 'Roles' article
   - [x] @cbeams to create stub at https://bisq.wiki/Roles
 - [ ] Seed the wiki with at least two reference examples of "good" role documentation
   - [x] https://bisq.wiki/Bisq_Maintainer (bisq-network/admin#39)
   - [ ] TBD
 - [ ] Assign role owners to create / update their own role documentation on the wiki
 - [ ] Respective team leads to review those new role articles

**Comment by cbeams** [comment]
- [ ] Change how we assign role issues, such that they are assigned to the team lead responsible for it, as opposed to be assigned to the owner(s) of that role. This is primarily to avoid duplication of information. The canonical source of information about who owns which role(s) is our various GitHub teams. Trying to replicate that information in the assignees list of each role issue guarantees drift between these two sources. It would be ideal if GitHub Issues allowed for assigning teams in a first-class way, but it does not. Another reason to assign the responsible team lead is that it better reflects who is responsible for oversight of this role in the sense of ensuring that its duties are being fulfilled, reviewing compensation requests related to it, etc.

**Comment by cbeams** [comment]
Closing as aborted. In practice, we've done quite a bit of cleaning up of roles and bonding over the last several months, but it didn't follow the process and tasks laid out here. We can still do a  better with managing roles, but for the most part things are working, and most role owners are up to date with their bonds. It's probably better at this point to simply close this project down and call things "good enough" for now.
